#!/bin/bash

if [ -z "$CC" ]; then
    CC="../toolchain/build/bin/x86_64-elf-gcc"
fi

if [ -z "$ASM" ]; then
    ASM=nasm
fi

if [ -z "$LD" ]; then
    LD="../toolchain/build/bin/x86_64-elf-ld"
fi

for i in $(find ./ -type f -name "*.c")
do
    $CC $i -Isrc/        \
    -std=gnu11           \
    -ffreestanding       \
    -fno-stack-protector \
    -fno-pic             \
    -Werror=implicit     \
    -Werror=implicit-function-declaration \
    -Werror=implicit-int \
    -Werror=int-conversion \
    -Werror=incompatible-pointer-types \
    -Werror=int-to-pointer-cast        \
    -mabi=sysv           \
    -mno-80387           \
    -mno-mmx             \
    -mno-3dnow           \
    -mno-sse             \
    -mno-sse2            \
    -mno-red-zone        \
    -mcmodel=kernel      \
    -MMD                 \
    -masm=intel          \
    -c                   \
    -o $i.o
done

for i in $(find ./ -type f -name "*.asm")
do
    $ASM $i -felf64 -o $i.o
done 


$LD $(find ./ -type f -name "*.o") -Tlinker.ld            \
    -nostdlib              \
    -zmax-page-size=0x1000 \
    -static                \
    -o kernel.sys          \
